[package]
name = "utopian"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.0"
ash = { version = "0.35.0", features = ["linked", "debug"]}
ash-window = "0.9"
shaderc = "0.7.3"
rspirv-reflect = "0.6.0"
image = "0.23.14"
