[package]
name = "utopian"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.0"
ash = { version = "0.35.0", features = ["linked", "debug"]}
ash-window = "0.9"
