#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_GOOGLE_include_directive : enable

#include "include/bindless.glsl"
#include "include/view.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout (std430, set = 2, binding = 0) writeonly buffer TestSSBO
{
   float test[512];
} testSSBO;

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);

    testSSBO.test[gid.x] = float(gid.x) / 512.0;
}